package com.students.preparation.matric.students;


import android.Manifest;
import android.content.Context;
import android.content.SharedPreferences;
import android.content.pm.PackageManager;
import android.net.ConnectivityManager;
import android.net.NetworkInfo;
import android.os.Build;
import android.telephony.TelephonyManager;
import android.util.DisplayMetrics;
import android.view.Display;

import androidx.appcompat.app.AppCompatActivity;

public class Constants {
    public static final String STORAGE_PATH_UPLOADS = "uploads/";
    public static final String LOGGED_STUDENTS_DATA = "studentsData";
    public static final String DATABASE_PATH_BOOKS = "books";
    public static final String DATABASE_PATH_WORKSHEET = "worksheet";
    public static final String DATABSE_TEACHERS_INBOX = "teachersInbox";
    public static final String DATABASE_PATH_REG_STUDENTS = "registered_students";
    public static final String DATABASE_PATH_APPROVED_STUDENTS = "approved_students";
    public static final String DATABASE_PATH_TEXTBOOKS = "textbooks";
    public static final String EXAM_FILES_PATH = "exams";
    public static final String DATABASE_PATH_REFERENCE_BOOKS = "reference_books";
    public static final String DATABASE_PATH_TUTORIALS="tutorials";
    public static final String DATABASE_PATH_PLASMA = "plasmas";
    public static final String DATABASE_PATH_NEWS = "news";
    public static final String DATABASE_PATH_TEACHERS_GUIDE = "teachers_guide";
    public static final String DATABASE_PATH_SHORTNOTES = "shortNotes";
    public static final String DATABASE_PATH_MY_SHORTNOTES = "my_short_notes";
    public static final String DATABASE_PATH_ENTRANCE_EXAM = "entrance_exam";
    public static final String DATABASE_PATH_MODEL_EXAM = "model_exam";
    public static final String DATABASE_PATH_STUDYTIPS = "studytips";
    public static final String DATABASE_PATH_ADMIN_UPLOADS = "admin_uploads";
    public static final String DATABASE_PATH_SOCIAL = "social";
    public static final String DATABASE_PATH_NATURAL = "natural";
    public static final String DATABASE_PATH_GRADE_11 = "11";
    public static final String DATABASE_PATH_GRADE_12 = "12";
    public static final String LOCALFILE_DOWNLOADS_PATH = "EntrancePreparation";

    public static final String HOME_KEY_ID = "home_key_id";
    public static final String HOME_KEY_THUMB_ICON = "home_key_thumb_icon";
    public static final String HOME_KEY_SUBTITLE = "home_key_subtitle";
    public static final String HOME_KEY_TITLE = "home_key_tite";

    public static final String TB_KEY_THUMB_ICON = "tb_key_thumb_icon";
    public static final String TB_KEY_SUBTITLE = "tb_key_subtitle";
    public static final String TB_KEY_TITLE = "tb_key_tite";

    public static final String EXAM_KEY_STREAM = "exam_stream";
    public static final String EXAM_KEY_SUBJECT = "exam_subject";
    public static final String EXAM_KEY_YEAR = "exam_year";

    public static final String EXAM_KEY_SUBJECT_MATH_S = "MathSocial";
    public static final String EXAM_KEY_SUBJECT_MATH_N = "MathNatural";

    public static final String EXAM_KEY_SUBJECT_ENGLISH = "English";
    public static final String EXAM_KEY_SUBJECT_PHYSICS = "Physics";
    public static final String EXAM_KEY_SUBJECT_BIOLOGY = "Biology";
    public static final String EXAM_KEY_SUBJECT_CHEMISTRY = "Chemistry";
    public static final String EXAM_KEY_SUBJECT_APTITUDE = "Aptitude";
    public static final String EXAM_KEY_SUBJECT_CIVIC = "Civic";

    public static final String EXAM_KEY_SUBJECT_GEOGRAPHY = "Geography";
    public static final String EXAM_KEY_SUBJECT_ECONOMICS = "Economics";
    public static final String EXAM_KEY_SUBJECT_HISTORY = "History";



    public static final String EXAM_QUESTION = "exam_question";
    public static final String EXAM_CHOICE_1 = "exam_choice_1";
    public static final String EXAM_CHOICE_2 = "exam_choice_2";
    public static final String EXAM_CHOICE_3 = "exam_choice_3";
    public static final String EXAM_CHOICE_4 = "exam_choice_4";
    public static final String EXAM_ANSWER = "exam_answer";
    public static final String EXAM_EXPLANATION = "exam_explanation";
    public static final String EXAM_OPTIONAL_IMAGE = "exam_optional_image";

    public static final String LOGGED_IN_USER_PHONE_NUMBER = "LOGGED_IN_USER_PHONE_NUMBER";
    public static final String LOGGED_IN_USER_FULL_NAME = "LOGGED_IN_USER_FULL_NAME";
    public static final String LOGGED_IN_USER_SCHOOL = "LOGGED_IN_USER_SCHOOL";
    public static final String LOGGED_IN_USER_STREAM = "LOGGED_IN_USER_STREAM";
    public static final String LOGGED_IN_USER_STUDENT_ID = "LOGGED_IN_USER_STUDENT_ID";

    public static final String DATABASE_PATH_TEACHERS = "teachers_uploads";
    public static final String LOGGED_IN_USER_IS_TEACHER = "teacher_logged_in";

    public static String[] schoolList = {
            "MAREMIYA A.A",
            "AB INF",
            "AB N2(YEKA)",
            "ABADO SEC. (P)",
            "ABIYOT QRS",
            "ABUNE GORGORIOS(ARADA)",
            "ABUNE GORGORIOS (NFAS SLK)",
            "ABYSSINIA",
            "ADEY ABEBA",
            "ADISS GLOBAL ",
            "ADISS KETEMA",
            "ADVENTIST",
            "AFRICA UNION  ",
            "AGAZIAN NO.3",
            "AKAKI KALEHIWET",
            "ALFA BILEN",
            "ALFA QERANIYO",
            "AMIGONIAS ",
            "ANDNET INTERNATIONAL ",
            "ANDODE",
            "ASAY",
            "ASKO ",
            "ASKO PROGRESS ",
            "ATLAS",
            "AWELIYA ",
            "AWELIYA N2",
            "AWZLIUM ",
            "AYER AMBA",
            "AYER XENA",
            "AYGODA",
            "BASHEWAM ",
            "BESEQA",
            "BESHALE ",
            "BETESEB",
            "BETHEL MEKANE EYESUS",
            "BETHLEHEM ",
            "BINGHAM",
            "BISRATE GEBRIEL ",
            "BKOLONS ",
            "BOLE COMMUNITY ",
            "BOLE KALEHIWOT",
            "BOLE PREPARATORY",
            "BRHAN GUZO ",
            "BRIGHT FUTURE ",
            "BRITISH INTERNATIONAL ",
            "BTIDI",
            "BULBULA",
            "BULBULA",
            "BURQA WAYE ",
            "CATHOLIC CATHEDRAL ",
            "CHARACTER HOLE CARK ",
            "CIATLE ",
            "D BALCHA ABA NEBSO",
            "D M PREPARATORY ",
            "DANDI BORU",
            "DEJ. BELAY ZELEQE",
            "DELIVERANCE (BOLE)",
            "DELIVERANCE (YEKA)",
            "DERARTU PREPARATORY ",
            "DIAMOND",
            "DIBORAH",
            "DILACHIN PREP.(A. KETEMA) ",
            "DILBER",
            "DOMBOSKO ",
            "DR. HADIS ALEMAYEHU",
            "DREAM SUCCESS ",
            "EDGET CHORA ",
            "EFOYTA",
            "ELBETHEL ",
            "ELBETHEL ACADEMY ",
            "ENAT",
            "ENTOTO WENGELAWIT ",
            "ENXOXO AMBA",
            "ERGB ",
            "ETHIO PARENT ",
            "ETHIO-HARVARD ",
            "ETHIO-JAPAN",
            "ETHIO-NATIONAL",
            "ETHIO-PARENTS ",
            "EWKET LE FRE ",
            "F L ADGEH ",
            "F TALENT",
            "FALCON ACADEMY",
            "FAMILY",
            "FANA 02",
            "FELEGE NEWAY ",
            "FIRHIWOT N2",
            "FIT. ABA. METAKIYA",
            "FNOTE LOZA",
            "FOUNTAIN OF KNOWLEDGE ",
            "FUTURE GENERATION ",
            "FUTURE HOPES",
            "GEDAM SITAWIAN ",
            "GELAN SECONDARY",
            "GENERAL TADESE BIRU ",
            "GIBSON (N. SLK)",
            "GIBSON (KOLFE)",
            "GINBOT 20",
            "GLORY ",
            "GREEK ",
            "HIDASE",
            "HILLSIDE ",
            "HOLYSAVIOR ",
            "IMPERIAL ",
            "INDIANA ",
            "ITALY (INTERNATIONAL)",
            "JIVA",
            "JOINT ",
            "KARA ALO SECONDARY",
            "KB",
            "KEFTEGNA 12",
            "KIDANE MHRET",
            "KOKEBE TSEBAH ",
            "KOLFE",
            "KOTEBE KIDANE MIHRET ",
            "KOYE",
            "LAFTO ",
            "LAZARIST CATHOLIC ",
            "LBAWI",
            "LEBU ",
            "LEM",
            "LEMLEM",
            "LESPRANCE ",
            "LIDETA MARIAM ",
            "LIZA",
            "M.M ST. GEBRIEL ",
            "MACMILLAN ",
            "MAGIC CARPET ",
            "MAGNET ",
            "MARIA RUBATO ",
            "ME’ERAF",
            "ME’ERAF (N. SLK)",
            "MEDHANIALEM ",
            "MERIT ",
            "MESKEREM",
            "MEWEDA",
            "MILLENNIUM ",
            "MILLENNIUM SEC. (YEKA) ",
            "MOUNT ",
            "MS. KELEMEWORK ",
            "MSKAYE HZUNAN",
            "MSRAQ GOH ",
            "NATHRET SCHOOL ",
            "NEJASHI",
            "NEW ENGLISH ",
            "NWAY CHALLENGE ",
            "OLIVE ",
            "ONE PLANET ",
            "PRESTIGIOUS",
            "Q. ANDARGE",
            "Q. MEDHANIALEM",
            "Q.S.K PREP",
            "QALITY ",
            "QDSTE MARIAM ",
            "QEBENA ADVENTIST ",
            "QECHENE D SELAM",
            "RADICAL ACADEMY (ARADA)",
            "RADICAL ACADEMY ",
            "RAGUEL (DHQR)",
            "RENESANS",
            "REPI",
            "REPI-ABEL",
            "RUFAEL HOLYSIVIOR ",
            "SAFARI ",
            "SCHOOL OF INDIANA",
            "SCHOOL OF READMISSION ",
            "SCHOOL OF TOMORROW (GULELE)",
            "SCHOOL OF TOMORROW (BOLE)",
            "SCHOOL OF TOMORROW (N. SLK)",
            "SCHOOL OF TOMORROW(YEKA) ",
            "SELAM N1",
            "SHBO EJERSA",
            "SHIMELS HABTE",
            "SINI SIDE",
            "SNNP",
            "AMHARA",
            "OROMIA",
            "BENISHANGUL",
            "HARARI ",
            "TIGRAY",
            "AFAR",
            "ADISS ABABA",
            "DIRE DAWA",
            "SOMALI",
            "GAMBELA",
            "SNZRO ",
            "SOUTH WEST ",
            "SOUTH WEST (NIFAS SLK)",
            "SPRING OF KNOWLEDGE ",
            "ST MICHAEL (YEKA)",
            "ST. JOHANNES ",
            "ST. JOSEPH ",
            "ST. MERRY ",
            "ST. MICHAEL(YEKA)",
            "ST. MIKAEL ",
            "SUMEYA",
            "SUPER HOLYSIVIOR ",
            "TAYM ACADEMY",
            "TESFA BIRHAN ",
            "TESFA DRJT ",
            "TIGAT 1",
            "TIKUR ANBESA",
            "TIPIFAY YOUTH ACADEMY",
            "TRILLIUM",
            "TULUDIMTU",
            "TWLD TESFA",
            "UNITY ",
            "VICTORY",
            "VISION ",
            "WENDIRAD",
            "XEMENJA",
            "Y R S",
            "YEHA",
            "YEKATIT 12",
            "YEKATIT 23",
            "YEKATIT SEC.",
            "YEMANEH BRHAN ",
            "YEMEN COMMUNITY (A. KETEMA)  ",
            "YETEBABERUT ",
            "ZOSKALES",
            "ABALA SEC.",
            "ARDI",
            "BERAHELE",
            "CHIFRA SEC. ",
            "CHIFRA SEC.",
            "DALOL HAIGER SEC.",
            "DUBTI SEC.",
            "ELIDAR SEC.",
            "GEWANE",
            "HADELEALA",
            "KELWAN",
            "KONEBA SEC.",
            "LOGIA SEC.",
            "MEHAMED BODAYA",
            "MELKA WERER",
            "MILL SEC.",
            "MOHAMED HANFERE",
            "NEMILEFEN",
            "SEMAR SECONDARY",
            "YENEGEW TESFA",
            "ABREHA WOATSIBEHA",
            "ADDIS KIDAME",
            "ADDIS ZEMEN PREP.",
            "AFERAWANAT",
            "AGEWI MEDEIR",
            "AMANUEAL",
            "AMBEKE",
            "ANBESAME",
            "ANDABIET",
            "ANEKESHA",
            "AYELECHI DEGEF METELAFIYA",
            "AZENA",
            "BAHIR DAR ACADEMY",
            "BAHIRDAR PREP.",
            "BAHIRE GIWERGIS",
            "BELAYE ZELEKE PREP.",
            "BTSUE G MICHALE",
            "CHAGNI PREP.",
            "CHARA",
            "CHEGAELY",
            "DAGMAWI TEWODROS PREP.",
            "REBU GEBEYA",
            "DANIGLA PREP.",
            "DEBER MARKOS PREP.",
            "DEBRE ELIAS",
            "DEBRE_WORK SEC.",
            "EBINAT",
            "ENGIBARA GEN. SEC.",
            "ETEGIA TEHATITU",
            "ETHIO-JAPAN",
            "FAGETA ",
            "FASILO",
            "FELGE BERHAN",
            "FENDIKA",
            "GASAYI",
            "GHION",
            "GINBOT 20",
            "GISSA",
            "GOH",
            "GOJJAM BER SEC.",
            "GOZAMEN GEN.",
            "JARA GEDO",
            "KIDEMAJAE",
            "KMIRDNGAYE",
            "KOMA AFSELDES",
            "KUY",
            "LEGA",
            "LEYEWU ASIRESE ZEWDIA",
            "MEKANE EYESUS",
            "MENIGESHA JENBERIY",
            "MENTA WUHA SEC.",
            "MESHENTY",
            "METAYA",
            "MKRIE SENIOR SEC.",
            "MOTA PREP.",
            "NEFAS MIWECHA PREP.",
            "REBU GEBEYA",
            "SATIMA DANGIA",
            "SEDIE",
            "SEWOCH LESEWOCH",
            "SHASHANA",
            "SOS HERMAN",
            "TANA HAIK SEC.",
            "TILILI",
            "WORKU JEMBER MTASEBIYA",
            "YEDWUHA",
            "YEJUBIE PREP.",
            "ZEGIE SEC.",
            "ZIGEM",
            "AGALO METI",
            "ASSOSA G.S.S SEC.",
            "BAMBASI SEC.",
            "BELOJIGANFOYE SEC.",
            "BERBER",
            "BULEN SEC.",
            "DEZA SEC.",
            "DIBATI M.S.S.",
            "EGANBONA EKONTE SEC.",
            "ENGINEER TIGRE DERESSA",
            "GALESA",
            "K2 M7 SEC.",
            "MAMBUK SEC.",
            "MANDURA",
            "MANKUSH SEC.",
            "MENGE G.SEC.",
            "PAWE SEC.",
            "TANABELES GIRLS BOARDING ",
            "TONGO MELES ZENAWI",
            "WOMBERA",
            "ADDIS HIWOT(DIRE)",
            "ADDISU(DIRE)",
            "ALFALAH",
            "BESRATE GABRIEL(DIRE)",
            "DIRE DAWA COMPREHENSIVE (DIRE)",
            "EMABETACHEN(DIRE)",
            "KIDIST TREZA (DIRE)",
            "MAHADL NUR ALISLAM ",
            "SABIAN SEC. (DIRE)",
            "ABOBO SEC.",
            "DIMMA SEC.",
            "GAMBELLA SEC.",
            "ITANG PERP.",
            "JAYINE SEC.",
            "KUWERGANG PERP.",
            "MATAR PREP.",
            "NIBNIB",
            "PIGNWUDO SEC.",
            "TERGOLE",
            "TINISHU METTI",
            "WINDYEW",
            "ABOKER PREP.",
            "BETHELHEM (HARAR)",
            "AW ABDAL INSTITUTE",
            "RAINBOW (HARAR)",
            "SOS HERMAN GEMEINNER SEC.",
            "MAICHEW SEC.",
            "WUKRO PREP.",
            "ABA G MICHEAL",
            "ABA-HILEMARIYAM",
            "ADI-DAERO PREP.",
            "ADIGUDOM SEC.",
            "ADI-HAGERAYE",
            "ADI-HAKI",
            "AGAZI SEC.",
            "AGEBA (SALE)",
            "AHESEA",
            "ALULA PREP.",
            "ATSBI SR.",
            "ATSEYOHANNSE",
            "AXUM PREP.",
            "AYDER SEC.",
            "BETMERA",
            "BIRUH-TESFA PREP.",
            "BORA",
            "BZET-SEC",
            "CHERCHER SR.",
            "Dr TSEGAY BERHE",
            "DAERO",
            "DAERO-HAFASH",
            "DANSHA PREP.",
            "DENGOLAT SEC.",
            "DEWHEN SR.",
            "EDAGA-HAMUS SR.",
            "EGELA SEC.",
            "ENDABAGUNA PREP.",
            "ESRAADIWEJERAT",
            "FENKL PREP.",
            "GELFAND FAMILY  ",
            "GETACHEW AZENAW SEC.",
            "GETACHEW WELDU SEC.",
            "GIDEY DEFTERA",
            "GJET PREP.",
            "HAHAYILE MESEN",
            "HAKIFEN PREP.",
            "HAWZIEN PRIPARATORY",
            "HEDASE EYASU BERHE ",
            "HINTSET SEC.",
            "HUMERA SEC.",
            "JIJIQA",
            "KALAMINO",
            "KALEB SEC.(TIGRAY)",
            "KALEB ACADEMY",
            "KETEMA NIGUS",
            "KIDAN MEHRET",
            "KINFE G MEDHIN ",
            "MAGIC-CARPET(TIGRAY)",
            "MAI-GABA",
            "MAIKADIRA",
            "MAI-TSEBRI SEC.",
            "MAY-AYENI",
            "MELES ZENAWI ",
            "MERCY(TIGRAY)",
            "MERE-MIEITY",
            "MEREWA",
            "MESEBO SEC.",
            "MELES ZENAWI PREP.",
            "SHERARO PREP.",
            "MESMERWEYANE SEC.",
            "MILLENNIUM OFLA",
            "NEJASNI ETHLO-TURKISH",
            "NIGSTSABA",
            "NIKOLAS.",
            "QAFTA",
            "RAMA",
            "SAMRE NEW",
            "SELEWA K  DEMTSU AMARE",
            "SEMEMA",
            "SHEBA ACADEMY",
            "SHIRE PREP.",
            "SMRET MERHATIBEB.",
            "SOS HERMAN GMEYNER",
            "SUHUL MICAEL MAHBEREDEGO",
            "TEKLI-SWUAT",
            "TIMUGA (WAJASR.S.)",
            "TSIGEREDA",
            "TSINSETA SR.",
            "W NGUS  SEC. ",
            "WERIE SEC.",
            "WERK-AMBA",
            "WUKROMARAY",
            "YECHILA MESNADAO",
            "YEMANE",
            "YIHA",
            "ZALAMBESA NEW",
            "ZANA PREP.",
            "ABAJEMA(R)",
            "ABENEZER(R)",
            "ABICHU GNA(P)",
            "ABOMSA(P)",
            "ABUNA GINDEBERET(P)",
            "ADELE(P)",
            "ADULALA(P)",
            "AGAMSA FINCHA(N)",
            "AGARO(P)",
            "AL-AFIA(R)",
            "ALGA(P)",
            "ALIBO(P)",
            "AMIGNA GASGAR(P)",
            "ANFILO(P)",
            "ANNO(P)",
            "ARJO(MOKONNON DAMSEW)(P)",
            "ASEBOT(P)",
            "ASENDABO(P)",
            "ASK (R)",
            "ASSELA(P)",
            "AWASH MELKA (P)",
            "BABILE(E.HARERGE)(P)",
            "BABOGAYA(R)",
            "BAKO(P)",
            "BALEMI(P)",
            "BANTU(P)",
            "BATU TERARA(P)",
            "BECHO(P)",
            "BEDELE(P)",
            "BEDESA(W.HARARGE)(P)",
            "BEKELCHA BARI(P)",
            "BELE (ARSI EAST)(P)",
            "BERKUME(P)",
            "BESS(BETHELEVANGELICAL(R)",
            "BETHEL ACADEMY(R)",
            "BIFTU AIRA(P)",
            "BIKILTU DEBASO(P)",
            "BIRBIRSA(P)",
            "BISHAN GURACHA(P)",
            "BISHOFTU(P)",
            "BITO TESSA-17(P)",
            "BOJI DERMEJI(P)",
            "BOKO(P)",
            "BORBOR(R)",
            "BORE(P)",
            "BORECHA(P)",
            "BOSET(P)",
            "BOTE(P)",
            "BRIGHT SIDE INT.ACA.(R)",
            "BULBULA(SHOA EAST)(P)",
            "BULCHANA(P)",
            "BULEHORA(R)",
            "BURE(P)",
            "BUSA(P)",
            "CHANCHO ABA-GEDA(P)",
            "CHANKA(R)",
            "CHELCHEL(P)",
            "CHELENKO(P)",
            "CHENKA(P)",
            "CHERCHER (W.HARARGIE)(P)",
            "CHOLE(P)",
            "CHORA(P)",
            "DABO TEMO(P)",
            "DAMA(P)",
            "DARIMU(P)",
            "DARME(P)",
            "DEBRE TSIGE(P)",
            "DEDER(P)",
            "DEDO(P)",
            "DEGA(P)",
            "DEJ.GERESU(P)",
            "DELO SEBRO(R)",
            "DENBEL(R)",
            "DIDEA ROBE(R)",
            "DIKSIS(R)",
            "DILO(R)",
            "DIMTU(R)",
            "DIRE ENCHINI(R)",
            "DODOLA SEC.  (P)",
            "DONGORO(R)",
            "DUKEM(R)",
            "DUMUGA(R)",
            "EJERE(R)",
            "ELEMO(R)",
            "ELWAYE(R)",
            "ENCHINI(P)",
            "EVEREST(R)",
            "FEKADE EGZEE(R)",
            "FINCHAWA (WEST GUJI)(P)",
            "FITCHE(P)",
            "GALLO(P)",
            "GAMBELA PREP.(W.WELL)(P)",
            "GATIRA(P)",
            "GECHI(P)",
            "GEDO(P)",
            "GELAN (GEBA ROBI)(P)",
            "GELEMSO(P)",
            "GEN.TADESE BIRU(EJERE)(P)",
            "GERBA(P)",
            "GIDA AYANA(P)",
            "GIMBI(R)",
            "GINCHI(R)",
            "GINDO(R)",
            "GIRAWA(R)",
            "GOHATSION(P)",
            "GORI(R)",
            "GORO MUTI(R)",
            "GOROGUTU(R)",
            "GUDAR(R)",
            "GUDAYA JARE(R)",
            "GUDINA SEYO(P)",
            "GURSUM(E.HARARGIE)(P)",
            "HARAMAYA UNIVERSITY(R)",
            "HARBU CHULULE(P)",
            "HAREMAYA(P)",
            "HARETO(P)",
            "HAWAS(P)",
            "HAYA DIMA(P)",
            "HIL TOPS(R)",
            "HIRNA(P)",
            "HOMA(R)",
            "HURUMU(P)",
            "HUSSE(P)",
            "IRBA MUDA(R)",
            "JARA(P)",
            "JARSO (WELLEGA)(P)",
            "JIDA(P)",
            "JIMMA MOLE SEC(R)",
            "JORGO NOLE(P)",
            "KALE AB(R)",
            "KEBE(P)",
            "KERCHAKULKULLE(P)",
            "KERSA (E.HARARGE)(P)",
            "KIDANE MIHRET(NEK.T.)(R)",
            "KIREMU(P)",
            "KOFELE(P)",
            "KOKOSA(P)",
            "KOMBOLCHA(WELLEGA)(P)",
            "KORE(P)",
            "KULUBI GEDAM(R)",
            "KUNI(R)",
            "KURFACHELE(R)",
            "KUYERA(P)",
            "LALO AIRA(R)",
            "LALO KILE(R)",
            "LEADSTAR(R)",
            "LEGETAFO(R)",
            "LEKA(R)",
            "LEMEN(R)",
            "LIBA(R)",
            "LIMU GALILA(R)",
            "LIMU GENET(R)",
            "MAKKO BILLI(R)",
            "MALKA SODA(P)",
            "MARY OUR HELP(R)",
            "MATI BORU(R)",
            "MECHARA (W.HARARGE)(P)",
            "MEGADO(P)",
            "MEGADO(R)",
            "MEGGA(R)",
            "MELKA MICHA(R)",
            "MENA(R)",
            "MENAGESHA KOLOBO(P)",
            "MENAGESHA KOLOBO(R)",
            "MENE SIBU(P)",
            "MENEBER.ADA NEG.ARSI(R)",
            "MERTI(P)",
            "MESELA(P)",
            "META GEFERSA(P)",
            "META GEFERSA(R)",
            "META WALKITE(R)",
            "METTU(R)",
            "MIDEGATOLA(P)",
            "MI'E BOKO(P)",
            "MILAMI(P)",
            "MINO(P)",
            "MIOO(P)",
            "MOJO(P)",
            "MOJO(R)",
            "MOTE(R)",
            "MOYALE(R)",
            "MUKETURI(P)",
            "NAFYAD (ADAMA)(R)",
            "NEGELLE(P)",
            "NEJO(P)",
            "NEKEMTE (R)",
            "NEKEMTE(P)",
            "NUNU(R)",
            "OBERA(P)",
            "ODA BOKOTA(P)",
            "ODA-SPECIAL BOARDING(R)",
            "PARADISE VALLEY (R)",
            "RIMETI(P)",
            "ROBE(P)",
            "ROBE(R)",
            "SAGURE(R)",
            "SEBETA (R)",
            "SEKA(P)",
            "SEKELA(P)",
            "SEKELA(R)",
            "SEKORU(R)",
            "SENA GENJI(P)",
            "SENDAFA (R)",
            "SERBO(P)",
            "SERBO(R)",
            "SEROFTA(P)",
            "SERU(P)",
            "SEYO(P)",
            "SHAKISO(N)",
            "SHAKISO(R)",
            "SHAMBU(R)",
            "SHASHEMENE(R)",
            "SHEBE(P)",
            "SHENAN(P)",
            "SHENO(P)",
            "SHER ETHIOPIA(R)",
            "SHINO(R)",
            "SHIRKA(R)",
            "SIBU SIRE(R)",
            "SIGMO (R)",
            "SIGMO(P)",
            "SILK AMBA(R)",
            "SILTANA(R)",
            "SIRARO(P)",
            "SIRE(P)",
            "SOS JIMMA(R)",
            "ST. JOSEPH (NAZARETH)(R)",
            "SUDE (KULA)(P)",
            "SUDE (KULA)(R)",
            "SULULTA(R)",
            "TARE(R)",
            "TAYFE(R)",
            "TEJI(P)",
            "TEJI(R)",
            "TEJO(R)",
            "TICHO(R)",
            "TOBA(R)",
            "TOLAY(R)",
            "TORE(R)",
            "TUKA(R)",
            "TULU MILKI(R)",
            "TULU WAYU(R)",
            "UKE(R)",
            "URAGA(R)",
            "WADERA(R)",
            "WATO(R)",
            "WAYU(R)",
            "WERKA(P)",
            "WETER(P)",
            "WONJI(P)",
            "WOREJIRU PREP.(P)",
            "YABELLO(P)",
            "YABELLO(R)",
            "YAYO(P)",
            "YEBU(P)",
            "YEHIBRET FRIE(P)",
            "YUBDO(P)",
            "ZEWAY DONBOSCO(R)",
            "AKEKA SEC.",
            "ALETAWONDO SEC.",
            "AMEYA  SEC.",
            "ANCUCHO SEC.",
            "ANESHO PREP.",
            "ABAS ALI SEC.",
            "ABDALE GADIID",
            "ABOKER SEC.",
            "ADADLE SEC.",
            "ANSHAX SEC.",
            "ARAARSO H.S",
            "ARE SCHOOL ",
            "AWARE SENIOR SEC",
            "AWBARRE SEC ",
            "AYINLE MELES SEC.",
            "AYSHIA AUGOSTO 13 G.SEC. ",
            "BABILE",
            "BEERCAANO SEC.",
            "BENANO BORDING SEC.",
            "BIKI H.S",
            "BIYO JANALE SEC.",
            "BOH PREP.",
            "BUR-UKUR SEC.",
            "D SARE LAANQAYR",
            "DAMBAL SEC.",
            "DANOOD SEC.",
            "DAROOR SEC.",
            "DEGAGO SEC.",
            "DEGAHA-BOUR SEC.",
            "DH WAYN SEC.",
            "DHEKA PREP.",
            "DOLLO-BAY PREP.",
            "DOLO ADDO SEC.",
            "DR.ABDUL MEJID HUSSEN S S S HA",
            "DUGSIGA HOYGA JIJIGA",
            "DUGSIGA SARE DHGAXLE",
            "DUGSIGA SARE EE DEG BAARE",
            "DUGSIGA SARE ERER",
            "DUGSIGA SARE M.M WAJALE",
            "EL - BAHAY SOC. ",
            "EL- KARRE SEC.",
            "FAARAX WARSAME",
            "FER-FER SEC.",
            "FIILTU SEC.",
            "FIK SECODRY",
            "GALLADI H.S",
            "GARBO PREP.",
            "GEERAARAW",
            "GODE PREP",
            "GUNAGADO H.S",
            "GURA BAQAQSA",
            "GURADAMOLE SEC.",
            "HARGELLE PREP.",
            "HARSHIN SEC.",
            "HASSEN JULUB",
            "HAYA SUFTU",
            "HUDAT SEC.",
            "JARRATI JUNIOR SEC.",
            "JIGJIGA COMMUNITY  ",
            "JIGJIGA SEC.",
            "K DAHAR PREP.",
            "KALI SEC.",
            "KALLAFO SEC.",
            "KEBRIBEYA SEC.",
            "LAFACISE SEC.",
            "LAGAHIDA SEC.",
            "MOYALE",
            "MUBARIK SEC.",
            "QALOOCAN H.  ",
            "RAASO SENIOR SEC. ",
            "RABASO SEC.",
            "SADAY SEC.",
            "SALAHAD SEC.",
            "SAYID M ABDULE SEC.",
            "SAYID MOHAMED",
            "SH.HUSSIEN ADE SEC.",
            "SH A SELAM SEC.",
            "SH DAHIR OMER",
            "SHAHDA SEC.",
            "SHEYKOSH SEC.",
            "SHILABO SENIOR SEC.",
            "SULDAAN CALI",
            "THE SPARRK",
            "UGASS XASAN HIRSI",
            "W ABDILLE SEC.",
            "WAJALE",
            "YOCALE SEC.",
            "YUCUB SEC.",};

    private static int realWidth,realHeight;
    public static String getDbName(){
        return "MatricDB";
    }


    public static  void calculateDeviceResolution(AppCompatActivity context) {
        Display display = context.getWindowManager().getDefaultDisplay();

        if (Build.VERSION.SDK_INT >= 17) {
            //new pleasant way to get real metrics
            DisplayMetrics realMetrics = new DisplayMetrics();
            display.getRealMetrics(realMetrics);
            setRealWidth(realMetrics.widthPixels);
            setRealHeight(realMetrics.heightPixels);

        } else {
            //This should be close, as lower API devices should not have window navigation bars
            setRealWidth(display.getWidth());
            setRealHeight(display.getHeight());
        }
    }

    public static String getStoragePathUploads() {
        return STORAGE_PATH_UPLOADS;
    }

    public static int getRealWidth() {
        return realWidth;
    }

    public static void setRealWidth(int realWidth) {
        Constants.realWidth = realWidth;
    }

    public static int getRealHeight() {
        return realHeight;
    }

    public static void setRealHeight(int realHeight) {
        Constants.realHeight = realHeight;
    }

    public static String getUniqueIdentifyer(Context context) {
        TelephonyManager telephonyManager;
        telephonyManager = (TelephonyManager)context.getSystemService(Context.
                TELEPHONY_SERVICE);
        /*
         * getDeviceId() returns the unique device ID.
         * For example,the IMEI for GSM and the MEID or ESN for CDMA phones.
         */
        //String deviceId = telephonyManager.getDeviceId();
        /*
         * getSubscriberId() returns the unique subscriber ID,
         * For example, the IMSI for a GSM phone.
         */
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
                if (context.checkSelfPermission(Manifest.permission.READ_PHONE_STATE) != PackageManager.PERMISSION_GRANTED) {
                    // TODO: Consider calling
                    //    Activity#requestPermissions
                    // here to request the missing permissions, and then overriding
                    //   public void onRequestPermissionsResult(int requestCode, String[] permissions,
                    //                                          int[] grantResults)
                    // to handle the case where the user grants the permission. See the documentation
                    // for Activity#requestPermissions for more details.

                    //subscriberId = telephonyManager.getSubscriberId();


                }
            }

            System.out.println("DEVICEID1 :" + telephonyManager.getDeviceId());
            return telephonyManager.getDeviceId();
    }

    public static String getLogedUserStream(Context context){
        SharedPreferences prefs = context.getSharedPreferences(Constants.LOGGED_IN_USER_FULL_NAME,0);
        return prefs.getString(Constants.LOGGED_IN_USER_STREAM, null);
    }

    public  static boolean isOnline(Context context){
        ConnectivityManager cm =  (ConnectivityManager)context.getSystemService(Context.CONNECTIVITY_SERVICE);
        NetworkInfo info = cm.getActiveNetworkInfo();
        if (info != null && info.isConnectedOrConnecting()){
            return true;
        }
        return false;
    }
}